import {
  mediaStateAfterProcessing,
  mediaStateMachine,
  originalIsServableToThirdParties,
  type DerivativeFileRole,
  type MediaState,
} from "@partybooth/contracts/media";
import type { Role } from "@partybooth/contracts/roles";
import { SIGNED_READ_URL_TTL_SECONDS, type SignedReadUrl } from "@partybooth/contracts/storage";
import { v } from "convex/values";

import type { Doc, Id } from "../_generated/dataModel";
import type { MutationCtx } from "../_generated/server";
import type { ReadCtx } from "./guards";
import { notifyPendingThreshold } from "./notifications";
import { resolveStorageAdapter } from "./storage";
import { mediaState, mediaType } from "./validators";

/**
 * The `media` row: creating it, moving it, counting it, and turning it into
 * something a client may see.
 *
 * The one rule that shapes this whole file is **idempotency by
 * `(eventId, captureId)`**. Two things independently announce that an upload
 * happened — the client, when its own request resolves, and the UploadThing
 * route handler, when the provider calls back — and they arrive in either order,
 * more than once each, on a party wifi network that drops packets. Every entry
 * point here therefore looks the row up by that pair first and *reconciles*,
 * rather than inserting and hoping.
 *
 * A concurrent double-insert is prevented by Convex rather than by a lock: two
 * mutations that both read "no row" and both insert are a write conflict, so one
 * commits and the other is re-executed against the committed state, where it
 * finds the row. That is also why nothing here caches a lookup across an `await`
 * that writes.
 */

/* -------------------------------------------------------------------------- */
/* Counters                                                                   */
/* -------------------------------------------------------------------------- */

type CountBucket = "pending" | "approved" | "declined";

/** Which denormalised counter a state belongs to, if any. */
function bucketOf(state: MediaState): CountBucket | null {
  switch (state) {
    case "pending":
    case "approved":
    case "declined":
      return state;
    // `processing` is in `total` but in none of the three: the organiser's
    // pending badge must not blink for a photo that is still uploading.
    // `deleted` is in nothing at all.
    default:
      return null;
  }
}

/** `"none"` is the state a row is in before it exists. */
export type PriorMediaState = MediaState | "none";

function countsIn(state: PriorMediaState): boolean {
  return state !== "none" && state !== "deleted";
}

/**
 * Move the event's counters to match a state change, in the same mutation that
 * made the change.
 *
 * Exact rather than eventually consistent, which is the point of denormalising
 * them at all: the pending badge on the organiser's phone is the thing that
 * tells them whether to keep moderating, and a badge that lags is a badge that
 * gets ignored.
 */
export async function applyCountChange(
  ctx: MutationCtx,
  eventId: Id<"events">,
  from: PriorMediaState,
  to: MediaState,
  now: number,
): Promise<void> {
  if (from === to) return;
  const event = await ctx.db.get(eventId);
  if (!event) return;

  const counts = { ...event.counts };

  const fromBucket = from === "none" ? null : bucketOf(from);
  const toBucket = bucketOf(to);
  if (fromBucket !== null) counts[fromBucket] = Math.max(0, counts[fromBucket] - 1);
  if (toBucket !== null) counts[toBucket] += 1;

  if (!countsIn(from) && countsIn(to)) counts.total += 1;
  if (countsIn(from) && !countsIn(to)) counts.total = Math.max(0, counts.total - 1);

  await ctx.db.patch(eventId, { counts, updatedAt: now });
}

/* -------------------------------------------------------------------------- */
/* Finding and creating                                                       */
/* -------------------------------------------------------------------------- */

export async function findMediaByCapture(
  ctx: ReadCtx,
  eventId: Id<"events">,
  captureId: string,
): Promise<Doc<"media"> | null> {
  return await ctx.db
    .query("media")
    .withIndex("by_event_and_capture", (q) => q.eq("eventId", eventId).eq("captureId", captureId))
    .unique();
}

/**
 * The row a grant describes, creating it in `processing` if it is not there yet.
 *
 * Everything on it comes from the **grant**, never from the caller: the grant is
 * the thing that was permission-checked and size-capped, so it is the only
 * honest source for byte size, type and checksum. A completion callback that
 * disagrees is a mismatch to be refused, not a correction to be applied.
 *
 * Returns `null` when the capture belongs to somebody else. `captureId` is
 * generated by the client and the index is scoped to the event rather than to
 * the person, so two guests at one party can name the same id — and a row is
 * owned by whoever got there first. `requestUploadGrant` already refuses to
 * issue a grant in that case; this is the second lock on the same door, because
 * the failure it prevents is one guest's photo appearing under another guest's
 * name, in their list, withdrawable only by them.
 */
export async function ensureMediaRow(
  ctx: MutationCtx,
  grant: Doc<"uploadGrants">,
  now: number,
): Promise<{ media: Doc<"media">; created: boolean } | null> {
  const existing = await findMediaByCapture(ctx, grant.eventId, grant.captureId);
  if (existing) {
    if (existing.uploaderUserId !== grant.userId) return null;
    return { media: existing, created: false };
  }

  const mediaId = await ctx.db.insert("media", {
    eventId: grant.eventId,
    uploaderUserId: grant.userId,
    captureId: grant.captureId,
    state: "processing",
    mediaType: grant.mediaType,
    grantId: grant._id,
    storageRegion: grant.storageRegion,
    byteSize: grant.byteSize,
    mimeType: grant.mimeType,
    checksum: grant.checksum,
    ...(grant.durationSeconds === undefined ? {} : { durationSeconds: grant.durationSeconds }),
    fromLibrary: grant.fromLibrary,
    ...(grant.sourceMetadataStripped === undefined
      ? {}
      : { sourceMetadataStripped: grant.sourceMetadataStripped }),
    ...(grant.sourceCarriesNoLocation === undefined
      ? {}
      : { sourceCarriesNoLocation: grant.sourceCarriesNoLocation }),
    ...(grant.capturedAt === undefined ? {} : { capturedAt: grant.capturedAt }),
    createdAt: now,
    updatedAt: now,
  });

  await applyCountChange(ctx, grant.eventId, "none", "processing", now);

  const media = await ctx.db.get(mediaId);
  if (!media) throw new Error("media row vanished immediately after insert");
  return { media, created: true };
}

/* -------------------------------------------------------------------------- */
/* Moving the state machine                                                   */
/* -------------------------------------------------------------------------- */

/**
 * Where an item lands once its bytes are safely stored, given the event's
 * moderation mode.
 *
 * The decision itself is the contract's (`mediaStateAfterProcessing`), so the
 * organiser console, the app and the backend cannot disagree about what
 * `automatic` means. `ai` behaves as `manual` until P1, by the same function.
 */
export async function settleAfterProcessing(
  ctx: MutationCtx,
  media: Doc<"media">,
  event: Doc<"events">,
  now: number,
): Promise<MediaState> {
  const next = mediaStateAfterProcessing(event.moderationMode);
  if (media.state === next) return next;

  // Throws `InvalidTransitionError` on an illegal move rather than writing one.
  mediaStateMachine.assertTransition(media.state, next);

  await ctx.db.patch(media._id, {
    state: next,
    // The slideshow's cursor. `automatic` mode approves here, with no host and
    // no decision row, so this is the only place that timestamp can come from.
    ...(next === "approved" ? { approvedAt: now } : {}),
    updatedAt: now,
  });
  await applyCountChange(ctx, media.eventId, media.state, next, now);

  /*
   * The host pending-queue ping hangs off this, and nothing else.
   *
   * This is the one place in the product where an item *becomes* something a
   * host has to act on — every other route into `pending` is a host's own
   * decision, and telling a host about a queue they just created is noise. The
   * counters are re-read rather than incremented locally because
   * `applyCountChange` is what maintains them and they are exact.
   *
   * `notifyPendingThreshold` swallows every ordinary reason not to send (no
   * devices, opted out, still under the threshold, already pinged this burst),
   * so this line cannot fail an upload. See `lib/notifications.ts`.
   */
  if (next === "pending") {
    const fresh = await ctx.db.get(media.eventId);
    if (fresh) {
      await notifyPendingThreshold(ctx, {
        event: fresh,
        pending: fresh.counts.pending,
        excludeUserId: media.uploaderUserId,
        now,
      });
    }
  }

  return next;
}

/* -------------------------------------------------------------------------- */
/* Derivatives                                                                */
/* -------------------------------------------------------------------------- */

/** Every provider key a media row currently names. */
export function storageKeysOf(media: Doc<"media">): string[] {
  return [media.storageKey, media.previewKey, media.posterKey].filter(
    (key): key is string => key !== undefined,
  );
}

export type DerivativeAttachment = "attached" | "duplicate" | "conflict";

/**
 * Attach a derivative object to the capture it belongs to.
 *
 * Idempotent on the **key**, exactly like the original's half of
 * `completeUpload` and for the same reason: the provider retries its callback,
 * and a retry has to change nothing. The three answers are the three things that
 * can be true —
 *
 * - `attached` — the column was empty and now names this object;
 * - `duplicate` — the column already names *this* object, so a callback has
 *   arrived twice and there is nothing to do;
 * - `conflict` — the column already names a **different** object. One capture
 *   has one preview; a second is bytes nobody asked for, and the caller deletes
 *   them.
 *
 * It deliberately does **not** touch `state`. A derivative landing does not
 * settle a capture and must not move the counters: the moderation queue counts
 * submissions, and a photo that arrives as three objects is one submission.
 * `settleAfterProcessing` stays the only thing that moves a row out of
 * `processing`, and it is driven by the original.
 */
export async function attachDerivative(
  ctx: MutationCtx,
  media: Doc<"media">,
  params: {
    role: DerivativeFileRole;
    fileKey: string;
    byteSize: number;
    /** The grant's checksum, kept so a later derivative cannot repeat this body. */
    checksum: string;
    /** The grant's location claim, read back by {@link mayServeDerivative}. */
    carriesNoLocation: boolean;
    now: number;
  },
): Promise<DerivativeAttachment> {
  const existing = params.role === "preview" ? media.previewKey : media.posterKey;
  if (existing === params.fileKey) return "duplicate";
  if (existing !== undefined) return "conflict";

  await ctx.db.patch(
    media._id,
    params.role === "preview"
      ? {
          previewKey: params.fileKey,
          previewByteSize: params.byteSize,
          previewChecksum: params.checksum,
          previewCarriesNoLocation: params.carriesNoLocation,
          updatedAt: params.now,
        }
      : {
          posterKey: params.fileKey,
          posterByteSize: params.byteSize,
          posterChecksum: params.checksum,
          posterCarriesNoLocation: params.carriesNoLocation,
          updatedAt: params.now,
        },
  );
  return "attached";
}

/**
 * Bytes this capture occupies in storage, as far as the record knows.
 *
 * Approximate on purpose, and the organiser-facing copy says so: it is the sum
 * of what the grants were issued for, not what the provider bills. Derivatives
 * are included because they are real objects — counting only originals told a
 * host a party was a third smaller than it is.
 */
export function storedBytesOf(media: Doc<"media">): number {
  return media.byteSize + (media.previewByteSize ?? 0) + (media.posterByteSize ?? 0);
}

/* -------------------------------------------------------------------------- */
/* Reading                                                                    */
/* -------------------------------------------------------------------------- */

/**
 * A media item as a client is allowed to see it.
 *
 * There is no `storageKey`, `previewKey` or `posterKey` in here, and there never
 * will be: a provider file key names an object directly, so handing one out
 * turns a permission-checked read into a bearer credential with no expiry. Read
 * paths return short-lived signed URLs and nothing else.
 */
export interface MediaView {
  id: Id<"media">;
  eventId: Id<"events">;
  captureId: string;
  state: MediaState;
  mediaType: Doc<"media">["mediaType"];
  fromLibrary: boolean;
  byteSize: number;
  mimeType: string;
  durationSeconds?: number;
  width?: number;
  height?: number;
  uploaderUserId: Id<"users">;
  uploaderDisplayName: string;
  isOwn: boolean;
  createdAt: number;
  capturedAt?: number;
  uploadedAt?: number;
  moderatedAt?: number;
  /** How many open reports. Present only for hosts — see {@link projectMedia}. */
  reportCount?: number;
  flaggedAt?: number;
  /**
   * The **original**. Absent while the item is still processing, when storage is
   * unreachable, and — for a viewer who is neither the submitter nor a host —
   * whenever the client did not confirm it stripped the metadata.
   */
  url?: string;
  urlExpiresAt?: number;
  /** The artefact a gallery renders: downscaled image, or short muted clip. */
  previewUrl?: string;
  previewUrlExpiresAt?: number;
  /** A video's still frame. Absent for photos. */
  posterUrl?: string;
  posterUrlExpiresAt?: number;
}

/**
 * The Convex validator for {@link MediaView}.
 *
 * It lives here, next to the interface it describes, because four function
 * modules now return this shape (`media`, `moderation`, `slideshow`, `stats`)
 * and a returns-validator copied into four files is three chances to add a field
 * to the type and not to the wire. Lib modules are not scanned for Convex
 * entry points, so a plain exported value is safe here and would not be in a
 * function module.
 */
export const mediaViewValidator = v.object({
  id: v.id("media"),
  eventId: v.id("events"),
  captureId: v.string(),
  state: mediaState,
  mediaType,
  fromLibrary: v.boolean(),
  byteSize: v.number(),
  mimeType: v.string(),
  durationSeconds: v.optional(v.number()),
  width: v.optional(v.number()),
  height: v.optional(v.number()),
  uploaderUserId: v.id("users"),
  uploaderDisplayName: v.string(),
  isOwn: v.boolean(),
  createdAt: v.number(),
  capturedAt: v.optional(v.number()),
  uploadedAt: v.optional(v.number()),
  moderatedAt: v.optional(v.number()),
  reportCount: v.optional(v.number()),
  flaggedAt: v.optional(v.number()),
  url: v.optional(v.string()),
  urlExpiresAt: v.optional(v.number()),
  previewUrl: v.optional(v.string()),
  previewUrlExpiresAt: v.optional(v.number()),
  posterUrl: v.optional(v.string()),
  posterUrlExpiresAt: v.optional(v.number()),
});

/**
 * Mint a signed URL, or give up quietly.
 *
 * A read path must not take the whole gallery down because one object is
 * unreachable or because the deployment has no storage credentials yet. The
 * caller renders an item with no image and a status line, which on party night
 * is enormously better than an error screen. The failure is logged once by the
 * adapter, not per item.
 */
async function safeUrl(
  region: Doc<"media">["storageRegion"],
  key: string | undefined,
  expiresInSeconds: number,
): Promise<SignedReadUrl | undefined> {
  if (key === undefined) return undefined;
  try {
    return await resolveStorageAdapter(region).createReadUrl(key, { expiresInSeconds });
  } catch {
    return undefined;
  }
}

export interface ProjectMediaOptions {
  viewerUserId: Id<"users">;
  /**
   * The viewer's role **for this event**. Decides who is allowed to be served an
   * original whose metadata was never confirmed stripped — see
   * {@link mayServeOriginal}.
   */
  viewerRole: Role;
  /** Overrides the default read TTL; see `SIGNED_READ_URL_TTL_SECONDS`. */
  expiresInSeconds?: number | undefined;
}

/**
 * May this viewer be served the **uploaded original**?
 *
 * The row carries the client's claim about its own bytes (ADR 0004 §7). It was
 * being recorded on the grant, copied to the row — and then read by nothing,
 * while `projectMedia` minted a URL for `storageKey` unconditionally. Since
 * Sprint 3 produced no derivative, that URL *is* the original: a guest bypassing
 * both first-party pipelines could upload a raw camera JPEG with a GPS fix
 * through the public `media.requestUploadGrant` mutation and have it served at
 * full resolution to everyone in the approved gallery. "Strip location metadata
 * from derivatives" then rested entirely on client self-attestation with no
 * consequence for a `false`.
 *
 * So the claim is load-bearing here, exactly as far as ADR 0004 §7 says it
 * should be: an unconfirmed original goes to **its submitter and the hosts** and
 * to nobody else. Hosts keep it because moderation is impossible without seeing
 * the thing being moderated, and because a host is the party's own data
 * controller rather than a third party; a fellow guest is a third party and gets
 * no URL at all.
 *
 * ## Which half of the claim this asks for
 *
 * Since Sprint 4 the claim has two halves (`MetadataClaim` in
 * `@partybooth/contracts/media`), and this one asks **"does it carry a
 * location?"** rather than **"was it re-encoded?"**. That is the question the
 * privacy invariant in PLAN.md is actually about, and the two stopped being the
 * same fact the moment video existed: no client can transcode a 60-second clip
 * in the time a guest will wait, but `apps/mobile` ships no location permission
 * on either platform and so can promise the location half honestly without
 * claiming the encoding half. Reading `sourceMetadataStripped` here would
 * withhold that clip from every fellow guest on the strength of a flag whose
 * name answers a different question.
 *
 * A row that predates the split answers both the same way, so nothing that is
 * already stored changes visibility — see `metadataClaimOf`.
 *
 * Derivatives are unaffected and are governed by the *other* half: a derivative
 * grant is **refused** unless it claims the re-encode
 * (`derivativeMetadataNotStripped`). That asymmetry is deliberate — on the
 * original the claim is recorded and read here, on a derivative it is a
 * precondition of the grant existing at all — and it is what lets this function
 * mean "serve the derivative instead" rather than "serve nothing".
 *
 * The "serve nothing" branch has **not** gone away: an item whose preview has
 * not landed yet — a phone that died between the two uploads — still shows a
 * fellow guest no image at all rather than an unverified original.
 */
function mayServeOriginal(media: Doc<"media">, viewer: { isOwn: boolean; role: Role }): boolean {
  if (originalIsServableToThirdParties(media)) return true;
  return viewer.isOwn || viewer.role === "owner" || viewer.role === "cohost";
}

/**
 * May this viewer be served a **derivative**?
 *
 * There used to be no read-time check on a derivative at all: `projectMedia`
 * minted `previewUrl` and `posterUrl` unconditionally, for every viewer, and the
 * only gate anywhere was the client-asserted re-encode claim that
 * `checkGrantEligibility` required at grant time. That made the derivative slot
 * the way around {@link mayServeOriginal} — upload the withheld original a second
 * time under `fileRole: "preview"` and it is served to the whole gallery.
 *
 * Two things close it, and this is the second of them. The first is
 * `checkDerivativeIsDistinct` in `media.ts`, which refuses a derivative whose
 * bytes are the original's; a genuine re-encode never reproduces its source. This
 * one carries the *location* half of the claim onto the derivative row and asks
 * the same question of it that `mayServeOriginal` asks of the original, so a
 * derivative that cannot promise it carries no location is withheld from third
 * parties instead of being trusted on the strength of `reEncoded` alone.
 *
 * A row that predates the column answers `undefined`, which inherits the
 * original's claim — so nothing already stored changes visibility.
 */
function mayServeDerivative(
  media: Doc<"media">,
  role: DerivativeFileRole,
  viewer: { isOwn: boolean; role: Role },
): boolean {
  if (viewer.isOwn || viewer.role === "owner" || viewer.role === "cohost") return true;
  const claimed =
    role === "preview" ? media.previewCarriesNoLocation : media.posterCarriesNoLocation;
  return claimed ?? originalIsServableToThirdParties(media);
}

/**
 * The name to show for an uploader.
 *
 * An account on its way out is anonymised on the **read path** rather than by
 * rewriting `users.displayName`, because the row still has to be recognisable
 * to an admin resolving an abuse report and to the audit trail. PLAN.md keeps
 * the media (it is the host's party, not the guest's alone) and drops the
 * attribution, and doing that here means it is true of every surface at once
 * rather than of whichever query remembered.
 */
function uploaderNameFor(uploader: Doc<"users"> | null): string {
  if (!uploader) return "Someone";
  if (uploader.accountState === "deletionScheduled" || uploader.accountState === "deleted") {
    return "Former guest";
  }
  return uploader.displayName;
}

export async function projectMedia(
  ctx: ReadCtx,
  media: Doc<"media">,
  options: ProjectMediaOptions,
): Promise<MediaView> {
  const ttl = options.expiresInSeconds ?? SIGNED_READ_URL_TTL_SECONDS;
  const uploader = await ctx.db.get(media.uploaderUserId);
  const isOwn = media.uploaderUserId === options.viewerUserId;
  const isHost = options.viewerRole === "owner" || options.viewerRole === "cohost";

  /*
   * A global admin is served **no file URL of any kind**, ever.
   *
   * PLAN.md: the admin console has "no media access", and `CAPABILITIES` gives
   * `globalAdmin` no `media.*` action at all — so in principle no admin can
   * reach this function, because every read path asks for a media capability
   * first. In principle is the problem. This is the single place a signed URL is
   * minted, so it is the single place the invariant can be made true rather than
   * implied, and the cost of stating it here is one comparison. A future query
   * that forgets its capability check leaks counts instead of photographs.
   *
   * Note this is *stricter* than `mayServeOriginal`, which would happily serve
   * an admin a metadata-stripped original: that function answers a privacy
   * question about the file, and this one answers a policy question about the
   * role.
   */
  const isAdmin = options.viewerRole === "globalAdmin";
  const viewer = { isOwn, role: options.viewerRole };
  const originalKey = !isAdmin && mayServeOriginal(media, viewer) ? media.storageKey : undefined;
  const previewKey =
    !isAdmin && mayServeDerivative(media, "preview", viewer) ? media.previewKey : undefined;
  const posterKey =
    !isAdmin && mayServeDerivative(media, "poster", viewer) ? media.posterKey : undefined;

  const [original, preview, poster] = await Promise.all([
    safeUrl(media.storageRegion, originalKey, ttl),
    // A photo with no preview yet falls back to its poster only because a video
    // that has a poster and no clip should still render *something*; a photo has
    // no poster, so this is a no-op for photos.
    safeUrl(media.storageRegion, previewKey ?? posterKey, ttl),
    safeUrl(media.storageRegion, posterKey, ttl),
  ]);

  return {
    id: media._id,
    eventId: media.eventId,
    captureId: media.captureId,
    state: media.state,
    mediaType: media.mediaType,
    fromLibrary: media.fromLibrary,
    byteSize: media.byteSize,
    mimeType: media.mimeType,
    ...(media.durationSeconds === undefined ? {} : { durationSeconds: media.durationSeconds }),
    ...(media.width === undefined ? {} : { width: media.width }),
    ...(media.height === undefined ? {} : { height: media.height }),
    uploaderUserId: media.uploaderUserId,
    uploaderDisplayName: uploaderNameFor(uploader),
    isOwn,
    createdAt: media.createdAt,
    ...(media.capturedAt === undefined ? {} : { capturedAt: media.capturedAt }),
    ...(media.uploadedAt === undefined ? {} : { uploadedAt: media.uploadedAt }),
    ...(media.moderatedAt === undefined ? {} : { moderatedAt: media.moderatedAt }),
    // Hosts only. A guest learning that three people reported the photo next to
    // theirs is a leak, and telling an uploader they have been reported turns a
    // report into a confrontation.
    ...(isHost && media.reportCount !== undefined ? { reportCount: media.reportCount } : {}),
    ...(isHost && media.flaggedAt !== undefined ? { flaggedAt: media.flaggedAt } : {}),
    ...(original === undefined ? {} : { url: original.url, urlExpiresAt: original.expiresAt }),
    ...(preview === undefined
      ? {}
      : { previewUrl: preview.url, previewUrlExpiresAt: preview.expiresAt }),
    ...(poster === undefined
      ? {}
      : { posterUrl: poster.url, posterUrlExpiresAt: poster.expiresAt }),
  };
}
