import {
  mediaStateAfterProcessing,
  mediaStateMachine,
  type MediaState,
} from "@partybooth/contracts/media";
import { SIGNED_READ_URL_TTL_SECONDS, type SignedReadUrl } from "@partybooth/contracts/storage";

import type { Doc, Id } from "../_generated/dataModel";
import type { MutationCtx } from "../_generated/server";
import type { ReadCtx } from "./guards";
import { resolveStorageAdapter } from "./storage";

/**
 * The `media` row: creating it, moving it, counting it, and turning it into
 * something a client may see.
 *
 * The one rule that shapes this whole file is **idempotency by
 * `(eventId, captureId)`**. Two things independently announce that an upload
 * happened — the client, when its own request resolves, and the UploadThing
 * route handler, when the provider calls back — and they arrive in either order,
 * more than once each, on a party wifi network that drops packets. Every entry
 * point here therefore looks the row up by that pair first and *reconciles*,
 * rather than inserting and hoping.
 *
 * A concurrent double-insert is prevented by Convex rather than by a lock: two
 * mutations that both read "no row" and both insert are a write conflict, so one
 * commits and the other is re-executed against the committed state, where it
 * finds the row. That is also why nothing here caches a lookup across an `await`
 * that writes.
 */

/* -------------------------------------------------------------------------- */
/* Counters                                                                   */
/* -------------------------------------------------------------------------- */

type CountBucket = "pending" | "approved" | "declined";

/** Which denormalised counter a state belongs to, if any. */
function bucketOf(state: MediaState): CountBucket | null {
  switch (state) {
    case "pending":
    case "approved":
    case "declined":
      return state;
    // `processing` is in `total` but in none of the three: the organiser's
    // pending badge must not blink for a photo that is still uploading.
    // `deleted` is in nothing at all.
    default:
      return null;
  }
}

/** `"none"` is the state a row is in before it exists. */
export type PriorMediaState = MediaState | "none";

function countsIn(state: PriorMediaState): boolean {
  return state !== "none" && state !== "deleted";
}

/**
 * Move the event's counters to match a state change, in the same mutation that
 * made the change.
 *
 * Exact rather than eventually consistent, which is the point of denormalising
 * them at all: the pending badge on the organiser's phone is the thing that
 * tells them whether to keep moderating, and a badge that lags is a badge that
 * gets ignored.
 */
export async function applyCountChange(
  ctx: MutationCtx,
  eventId: Id<"events">,
  from: PriorMediaState,
  to: MediaState,
  now: number,
): Promise<void> {
  if (from === to) return;
  const event = await ctx.db.get(eventId);
  if (!event) return;

  const counts = { ...event.counts };

  const fromBucket = from === "none" ? null : bucketOf(from);
  const toBucket = bucketOf(to);
  if (fromBucket !== null) counts[fromBucket] = Math.max(0, counts[fromBucket] - 1);
  if (toBucket !== null) counts[toBucket] += 1;

  if (!countsIn(from) && countsIn(to)) counts.total += 1;
  if (countsIn(from) && !countsIn(to)) counts.total = Math.max(0, counts.total - 1);

  await ctx.db.patch(eventId, { counts, updatedAt: now });
}

/* -------------------------------------------------------------------------- */
/* Finding and creating                                                       */
/* -------------------------------------------------------------------------- */

export async function findMediaByCapture(
  ctx: ReadCtx,
  eventId: Id<"events">,
  captureId: string,
): Promise<Doc<"media"> | null> {
  return await ctx.db
    .query("media")
    .withIndex("by_event_and_capture", (q) => q.eq("eventId", eventId).eq("captureId", captureId))
    .unique();
}

/**
 * The row a grant describes, creating it in `processing` if it is not there yet.
 *
 * Everything on it comes from the **grant**, never from the caller: the grant is
 * the thing that was permission-checked and size-capped, so it is the only
 * honest source for byte size, type and checksum. A completion callback that
 * disagrees is a mismatch to be refused, not a correction to be applied.
 *
 * Returns `null` when the capture belongs to somebody else. `captureId` is
 * generated by the client and the index is scoped to the event rather than to
 * the person, so two guests at one party can name the same id — and a row is
 * owned by whoever got there first. `requestUploadGrant` already refuses to
 * issue a grant in that case; this is the second lock on the same door, because
 * the failure it prevents is one guest's photo appearing under another guest's
 * name, in their list, withdrawable only by them.
 */
export async function ensureMediaRow(
  ctx: MutationCtx,
  grant: Doc<"uploadGrants">,
  now: number,
): Promise<{ media: Doc<"media">; created: boolean } | null> {
  const existing = await findMediaByCapture(ctx, grant.eventId, grant.captureId);
  if (existing) {
    if (existing.uploaderUserId !== grant.userId) return null;
    return { media: existing, created: false };
  }

  const mediaId = await ctx.db.insert("media", {
    eventId: grant.eventId,
    uploaderUserId: grant.userId,
    captureId: grant.captureId,
    state: "processing",
    mediaType: grant.mediaType,
    grantId: grant._id,
    storageRegion: grant.storageRegion,
    byteSize: grant.byteSize,
    mimeType: grant.mimeType,
    checksum: grant.checksum,
    ...(grant.durationSeconds === undefined ? {} : { durationSeconds: grant.durationSeconds }),
    fromLibrary: grant.fromLibrary,
    ...(grant.sourceMetadataStripped === undefined
      ? {}
      : { sourceMetadataStripped: grant.sourceMetadataStripped }),
    ...(grant.capturedAt === undefined ? {} : { capturedAt: grant.capturedAt }),
    createdAt: now,
    updatedAt: now,
  });

  await applyCountChange(ctx, grant.eventId, "none", "processing", now);

  const media = await ctx.db.get(mediaId);
  if (!media) throw new Error("media row vanished immediately after insert");
  return { media, created: true };
}

/* -------------------------------------------------------------------------- */
/* Moving the state machine                                                   */
/* -------------------------------------------------------------------------- */

/**
 * Where an item lands once its bytes are safely stored, given the event's
 * moderation mode.
 *
 * The decision itself is the contract's (`mediaStateAfterProcessing`), so the
 * organiser console, the app and the backend cannot disagree about what
 * `automatic` means. `ai` behaves as `manual` until P1, by the same function.
 */
export async function settleAfterProcessing(
  ctx: MutationCtx,
  media: Doc<"media">,
  event: Doc<"events">,
  now: number,
): Promise<MediaState> {
  const next = mediaStateAfterProcessing(event.moderationMode);
  if (media.state === next) return next;

  // Throws `InvalidTransitionError` on an illegal move rather than writing one.
  mediaStateMachine.assertTransition(media.state, next);

  await ctx.db.patch(media._id, { state: next, updatedAt: now });
  await applyCountChange(ctx, media.eventId, media.state, next, now);
  return next;
}

/* -------------------------------------------------------------------------- */
/* Reading                                                                    */
/* -------------------------------------------------------------------------- */

/**
 * A media item as a client is allowed to see it.
 *
 * There is no `storageKey`, `previewKey` or `posterKey` in here, and there never
 * will be: a provider file key names an object directly, so handing one out
 * turns a permission-checked read into a bearer credential with no expiry. Read
 * paths return short-lived signed URLs and nothing else.
 */
export interface MediaView {
  id: Id<"media">;
  eventId: Id<"events">;
  captureId: string;
  state: MediaState;
  mediaType: Doc<"media">["mediaType"];
  fromLibrary: boolean;
  byteSize: number;
  mimeType: string;
  durationSeconds?: number;
  width?: number;
  height?: number;
  uploaderUserId: Id<"users">;
  uploaderDisplayName: string;
  isOwn: boolean;
  createdAt: number;
  capturedAt?: number;
  uploadedAt?: number;
  moderatedAt?: number;
  /** Absent while the item is still processing, or when storage is unreachable. */
  url?: string;
  urlExpiresAt?: number;
  previewUrl?: string;
  previewUrlExpiresAt?: number;
}

/**
 * Mint a signed URL, or give up quietly.
 *
 * A read path must not take the whole gallery down because one object is
 * unreachable or because the deployment has no storage credentials yet. The
 * caller renders an item with no image and a status line, which on party night
 * is enormously better than an error screen. The failure is logged once by the
 * adapter, not per item.
 */
async function safeUrl(
  region: Doc<"media">["storageRegion"],
  key: string | undefined,
  expiresInSeconds: number,
): Promise<SignedReadUrl | undefined> {
  if (key === undefined) return undefined;
  try {
    return await resolveStorageAdapter(region).createReadUrl(key, { expiresInSeconds });
  } catch {
    return undefined;
  }
}

export interface ProjectMediaOptions {
  viewerUserId: Id<"users">;
  /** Overrides the default read TTL; see `SIGNED_READ_URL_TTL_SECONDS`. */
  expiresInSeconds?: number | undefined;
}

export async function projectMedia(
  ctx: ReadCtx,
  media: Doc<"media">,
  options: ProjectMediaOptions,
): Promise<MediaView> {
  const ttl = options.expiresInSeconds ?? SIGNED_READ_URL_TTL_SECONDS;
  const uploader = await ctx.db.get(media.uploaderUserId);

  const [original, preview] = await Promise.all([
    safeUrl(media.storageRegion, media.storageKey, ttl),
    safeUrl(media.storageRegion, media.previewKey ?? media.posterKey, ttl),
  ]);

  return {
    id: media._id,
    eventId: media.eventId,
    captureId: media.captureId,
    state: media.state,
    mediaType: media.mediaType,
    fromLibrary: media.fromLibrary,
    byteSize: media.byteSize,
    mimeType: media.mimeType,
    ...(media.durationSeconds === undefined ? {} : { durationSeconds: media.durationSeconds }),
    ...(media.width === undefined ? {} : { width: media.width }),
    ...(media.height === undefined ? {} : { height: media.height }),
    uploaderUserId: media.uploaderUserId,
    uploaderDisplayName: uploader?.displayName ?? "Someone",
    isOwn: media.uploaderUserId === options.viewerUserId,
    createdAt: media.createdAt,
    ...(media.capturedAt === undefined ? {} : { capturedAt: media.capturedAt }),
    ...(media.uploadedAt === undefined ? {} : { uploadedAt: media.uploadedAt }),
    ...(media.moderatedAt === undefined ? {} : { moderatedAt: media.moderatedAt }),
    ...(original === undefined ? {} : { url: original.url, urlExpiresAt: original.expiresAt }),
    ...(preview === undefined
      ? {}
      : { previewUrl: preview.url, previewUrlExpiresAt: preview.expiresAt }),
  };
}
